# Generated by Django 5.2.2 on 2025-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_fitnessclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
